vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.fillchars='eob: '
vim.opt.mouse = 'a'
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.hlsearch = false
vim.opt.wrap = true
vim.opt.breakindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.signcolumn = "no"
vim.opt.cursorline = true
